import Chart from "@/components/Chart";
import Heading from "@/components/Heading";
import Search from "@/components/Search";
import { Container } from "@/styles/Home.styled";
import { Container as Container1 } from "@/styles/Heading.styled";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container1>
        <Heading />
        <Container>
          <Search />
          <Chart />
        </Container>
      </Container1>
    </>
  );
}
